# Generated by Django 2.2.2 on 2019-06-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timecard', '0002_timesheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='site_code',
            field=models.CharField(max_length=250),
        ),
    ]
